--Cocktails: 

INSERT INTO co.t_cocktails VALUES (1, 'Alexander', 'https://en.wikipedia.org/wiki/Alexander_(cocktail)');
INSERT INTO co.t_cocktails VALUES (2, 'Americano - Lo prendi nell''ano', 'https://en.wikipedia.org/wiki/Americano_(cocktail)');
INSERT INTO co.t_cocktails VALUES (3, 'Angel Face', 'https://en.wikipedia.org/wiki/Angel_Face_(cocktail)');
INSERT INTO co.t_cocktails VALUES (4, 'Aviation', 'https://en.wikipedia.org/wiki/Aviation_(cocktail)');
INSERT INTO co.t_cocktails VALUES (5, 'Between the Sheets', 'https://en.wikipedia.org/wiki/Between_the_Sheets_(cocktail)');
INSERT INTO co.t_cocktails VALUES (6, 'Boulevardier', 'https://en.wikipedia.org/wiki/Boulevardier_(cocktail)');
INSERT INTO co.t_cocktails VALUES (7, 'Brandy Crusta', 'https://en.wikipedia.org/wiki/Brandy_Crusta');
INSERT INTO co.t_cocktails VALUES (8, 'Casino', 'https://en.wikipedia.org/wiki/Casino_(cocktail)');
INSERT INTO co.t_cocktails VALUES (9, 'Clover Club Cocktail', 'https://en.wikipedia.org/wiki/Clover_Club_Cocktail');
INSERT INTO co.t_cocktails VALUES (10, 'Daiquiri', 'https://en.wikipedia.org/wiki/Daiquiri');
INSERT INTO co.t_cocktails VALUES (11, 'Dry Martini', 'https://en.wikipedia.org/wiki/Martini_(cocktail)');
INSERT INTO co.t_cocktails VALUES (12, 'Fizz', 'https://en.wikipedia.org/wiki/Fizz_(cocktail)#Gin_fizz');
INSERT INTO co.t_cocktails VALUES (13, 'Hanky Panky', 'https://en.wikipedia.org/wiki/Hanky_Panky_(cocktail)');
INSERT INTO co.t_cocktails VALUES (14, 'John Collins', 'https://en.wikipedia.org/wiki/John_Collins_(cocktail)');
INSERT INTO co.t_cocktails VALUES (15, 'The Last Word', 'https://en.wikipedia.org/wiki/Last_Word_(cocktail)');
INSERT INTO co.t_cocktails VALUES (16, 'Manhattan', 'https://en.wikipedia.org/wiki/Manhattan_(cocktail)');
INSERT INTO co.t_cocktails VALUES (17, 'Martinez', 'https://en.wikipedia.org/wiki/Martinez_(cocktail)');
INSERT INTO co.t_cocktails VALUES (18, 'Mary Pickford', 'https://en.wikipedia.org/wiki/Mary_Pickford_(cocktail)');
INSERT INTO co.t_cocktails VALUES (19, 'Monkey Gland', 'https://en.wikipedia.org/wiki/Monkey_Gland');
INSERT INTO co.t_cocktails VALUES (20, 'Negroni', 'https://en.wikipedia.org/wiki/Negroni');
INSERT INTO co.t_cocktails VALUES (21, 'Old fashioned', 'https://en.wikipedia.org/wiki/Old_fashioned_(cocktail)');
INSERT INTO co.t_cocktails VALUES (22, 'Paradise', 'https://en.wikipedia.org/wiki/Paradise_(cocktail)');
INSERT INTO co.t_cocktails VALUES (23, 'Planter''s punch', 'https://en.wikipedia.org/wiki/Planter%27s_punch');
INSERT INTO co.t_cocktails VALUES (24, 'Porto Flip', 'https://en.wikipedia.org/wiki/Porto_flip');
INSERT INTO co.t_cocktails VALUES (25, 'Fizz', 'https://en.wikipedia.org/wiki/Fizz_(cocktail)#Ramos_gin_fizz');
INSERT INTO co.t_cocktails VALUES (26, 'Rusty Nail', 'https://en.wikipedia.org/wiki/Rusty_Nail_(cocktail)');
INSERT INTO co.t_cocktails VALUES (27, 'Sazerac', 'https://en.wikipedia.org/wiki/Sazerac');
INSERT INTO co.t_cocktails VALUES (28, 'Sidecar', 'https://en.wikipedia.org/wiki/Sidecar_(cocktail)');
INSERT INTO co.t_cocktails VALUES (29, 'Stinger', 'https://en.wikipedia.org/wiki/Stinger_(cocktail)');
INSERT INTO co.t_cocktails VALUES (30, 'Tuxedo', 'https://en.wikipedia.org/wiki/Tuxedo_(cocktail)');
INSERT INTO co.t_cocktails VALUES (31, 'Vieux Carré', 'https://en.wikipedia.org/wiki/Vieux_Carr%C3%A9_(cocktail)');
INSERT INTO co.t_cocktails VALUES (32, 'Whiskey Sour', 'https://en.wikipedia.org/wiki/Whiskey_sour');
INSERT INTO co.t_cocktails VALUES (33, 'White Lady', 'https://en.wikipedia.org/wiki/White_Lady_(cocktail)');
INSERT INTO co.t_cocktails VALUES (34, 'Bellini', 'https://en.wikipedia.org/wiki/Bellini_(cocktail)');
INSERT INTO co.t_cocktails VALUES (35, 'Black Russian', 'https://en.wikipedia.org/wiki/Black_Russian');
INSERT INTO co.t_cocktails VALUES (36, 'Bloody Mary', 'https://en.wikipedia.org/wiki/Bloody_Mary_(cocktail)');
INSERT INTO co.t_cocktails VALUES (37, 'Caipirinha', 'https://en.wikipedia.org/wiki/Caipirinha');
INSERT INTO co.t_cocktails VALUES (38, 'Champagne Cocktail', 'https://en.wikipedia.org/wiki/Champagne_cocktail');
INSERT INTO co.t_cocktails VALUES (39, 'Corpse Reviver №1', 'https://en.wikipedia.org/wiki/Corpse_Reviver_(cocktail)#Corpse_Reviver_№2_&_№2A');
INSERT INTO co.t_cocktails VALUES (40, 'Cosmopolitan', 'https://en.wikipedia.org/wiki/Cosmopolitan_(cocktail)');
INSERT INTO co.t_cocktails VALUES (41, 'Rum and Coke Cuba libre', 'https://en.wikipedia.org/wiki/Cuba_libre');
INSERT INTO co.t_cocktails VALUES (42, 'French 75', 'https://en.wikipedia.org/wiki/French_75_(cocktail)');
INSERT INTO co.t_cocktails VALUES (43, 'French Connection', 'https://en.wikipedia.org/wiki/French_Connection_(cocktail)');
INSERT INTO co.t_cocktails VALUES (44, 'Golden Dream', 'https://en.wikipedia.org/wiki/Golden_dream_(cocktail)');
INSERT INTO co.t_cocktails VALUES (45, 'Grasshopper', 'https://en.wikipedia.org/wiki/Grasshopper_(cocktail)');
INSERT INTO co.t_cocktails VALUES (46, 'Hemingway Special', 'https://en.wikipedia.org/wiki/Hemingway_Special');
INSERT INTO co.t_cocktails VALUES (47, 'Horse''s Neck', 'https://en.wikipedia.org/wiki/Horse%27s_Neck');
INSERT INTO co.t_cocktails VALUES (48, 'Irish Coffee', 'https://en.wikipedia.org/wiki/Irish_coffee');
INSERT INTO co.t_cocktails VALUES (49, 'Kir', 'https://en.wikipedia.org/wiki/Kir_(cocktail)');
INSERT INTO co.t_cocktails VALUES (50, 'Long Island Iced Tea', 'https://en.wikipedia.org/wiki/Long_Island_iced_tea');
INSERT INTO co.t_cocktails VALUES (51, 'Mai Tai', 'https://en.wikipedia.org/wiki/Mai_Tai');
INSERT INTO co.t_cocktails VALUES (52, 'Margarita', 'https://en.wikipedia.org/wiki/Margarita');
INSERT INTO co.t_cocktails VALUES (53, 'Mimosa', 'https://en.wikipedia.org/wiki/Mimosa_(cocktail)');
INSERT INTO co.t_cocktails VALUES (54, 'Mint julep', 'https://en.wikipedia.org/wiki/Mint_julep');
INSERT INTO co.t_cocktails VALUES (55, 'Mojito', 'https://en.wikipedia.org/wiki/Mojito');
INSERT INTO co.t_cocktails VALUES (56, 'Moscow mule', 'https://en.wikipedia.org/wiki/Moscow_mule');
INSERT INTO co.t_cocktails VALUES (57, 'Piña Colada', 'https://en.wikipedia.org/wiki/Pi%C3%B1a_Colada');
INSERT INTO co.t_cocktails VALUES (58, 'Pisco Sour', 'https://en.wikipedia.org/wiki/Pisco_Sour');
INSERT INTO co.t_cocktails VALUES (59, 'Sea Breeze', 'https://en.wikipedia.org/wiki/Sea_Breeze_(cocktail)');
INSERT INTO co.t_cocktails VALUES (60, 'Sex on the Beach', 'https://en.wikipedia.org/wiki/Sex_on_the_Beach');
INSERT INTO co.t_cocktails VALUES (61, 'Singapore Sling', 'https://en.wikipedia.org/wiki/Singapore_Sling');
INSERT INTO co.t_cocktails VALUES (62, 'Tequila sunrise', 'https://en.wikipedia.org/wiki/Tequila_Sunrise_(cocktail)');
INSERT INTO co.t_cocktails VALUES (63, 'Vesper', 'https://en.wikipedia.org/wiki/Vesper_(cocktail)');
INSERT INTO co.t_cocktails VALUES (64, 'Zombie', 'https://en.wikipedia.org/wiki/Zombie_(cocktail)');
INSERT INTO co.t_cocktails VALUES (65, 'Barracuda', 'https://en.wikipedia.org/wiki/Barracuda_(cocktail)');
INSERT INTO co.t_cocktails VALUES (66, 'Bee''s Knees', 'https://en.wikipedia.org/wiki/Bee%27s_Knees_(cocktail)');
INSERT INTO co.t_cocktails VALUES (67, 'Bramble', 'https://en.wikipedia.org/wiki/Bramble_(cocktail)');
INSERT INTO co.t_cocktails VALUES (68, 'Canchanchara', 'https://en.wikipedia.org/wiki/Canchanchara');
INSERT INTO co.t_cocktails VALUES (69, 'Dark ''n'' Stormy', 'https://en.wikipedia.org/wiki/Dark_%27n%27_Stormy');
INSERT INTO co.t_cocktails VALUES (70, 'Espresso martini', 'https://en.wikipedia.org/wiki/Espresso_martini');
INSERT INTO co.t_cocktails VALUES (71, 'Fernandito', 'https://en.wikipedia.org/wiki/Fernandito');
INSERT INTO co.t_cocktails VALUES (72, 'French martini', 'https://en.wikipedia.org/wiki/French_martini');
INSERT INTO co.t_cocktails VALUES (73, 'Illegal', 'https://en.wikipedia.org/wiki/Illegal_(cocktail)');
INSERT INTO co.t_cocktails VALUES (74, 'Lemon Drop', 'https://en.wikipedia.org/wiki/Lemon_drop_martini');
INSERT INTO co.t_cocktails VALUES (75, 'Naked and Famous', 'https://en.wikipedia.org/wiki/Naked_and_Famous_(cocktail)');
INSERT INTO co.t_cocktails VALUES (76, 'New York Sour', 'https://en.wikipedia.org/wiki/New_York_Sour');
INSERT INTO co.t_cocktails VALUES (77, 'Old Cuban', 'https://en.wikipedia.org/wiki/Old_Cuban');
INSERT INTO co.t_cocktails VALUES (78, 'Paloma', 'https://en.wikipedia.org/wiki/Paloma_(cocktail)');
INSERT INTO co.t_cocktails VALUES (79, 'Paper Plane', 'https://en.wikipedia.org/wiki/Paper_Plane_(cocktail)');
INSERT INTO co.t_cocktails VALUES (80, 'Penicillin', 'https://en.wikipedia.org/wiki/Penicillin_(cocktail)');
INSERT INTO co.t_cocktails VALUES (81, 'Russian Spring Punch', 'https://en.wikipedia.org/wiki/Russian_Spring_Punch');
INSERT INTO co.t_cocktails VALUES (82, 'South Side or Southside', 'https://en.wikipedia.org/wiki/Southside_(cocktail)');
INSERT INTO co.t_cocktails VALUES (83, 'Spritz', 'https://en.wikipedia.org/wiki/Spritz_Veneziano');
INSERT INTO co.t_cocktails VALUES (84, 'Suffering Bastard', 'https://en.wikipedia.org/wiki/Suffering_Bastard');
INSERT INTO co.t_cocktails VALUES (85, 'Tipperary', 'https://en.wikipedia.org/wiki/Tipperary_(cocktail)');
INSERT INTO co.t_cocktails VALUES (86, 'Tommy''s margarita', 'https://en.wikipedia.org/wiki/Tommy%27s_margarita');
INSERT INTO co.t_cocktails VALUES (87, 'Trinidad Sour', 'https://en.wikipedia.org/wiki/Trinidad_Sour');
INSERT INTO co.t_cocktails VALUES (88, 'Ve.n.to', 'https://en.wikipedia.org/wiki/Ve.n.to');
INSERT INTO co.t_cocktails VALUES (89, 'Yellow Bird', 'https://en.wikipedia.org/wiki/Yellow_Bird_(cocktail)');

SELECT pg_catalog.setval('co.t_cocktails_cocktail_id_seq', 89, true);

--Ingredients: 

INSERT INTO co.ingredients VALUES (1, 'cognac');
INSERT INTO co.ingredients VALUES (2, 'crème de cacao');
INSERT INTO co.ingredients VALUES (3, 'cream');
INSERT INTO co.ingredients VALUES (4, 'vermouth');
INSERT INTO co.ingredients VALUES (5, 'campari');
INSERT INTO co.ingredients VALUES (6, 'soda water');
INSERT INTO co.ingredients VALUES (7, 'gin');
INSERT INTO co.ingredients VALUES (8, 'calvados');
INSERT INTO co.ingredients VALUES (9, 'apricot brandy');
INSERT INTO co.ingredients VALUES (10, 'maraschino');
INSERT INTO co.ingredients VALUES (11, 'crème de violette');
INSERT INTO co.ingredients VALUES (12, 'rum');
INSERT INTO co.ingredients VALUES (13, 'triple sec');
INSERT INTO co.ingredients VALUES (14, 'white rum');
INSERT INTO co.ingredients VALUES (15, 'lemon juice');
INSERT INTO co.ingredients VALUES (16, 'bourbon whiskey');
INSERT INTO co.ingredients VALUES (17, 'bourbon');
INSERT INTO co.ingredients VALUES (18, 'brandy');
INSERT INTO co.ingredients VALUES (19, 'maraschino luxardo');
INSERT INTO co.ingredients VALUES (20, 'curaçao');
INSERT INTO co.ingredients VALUES (21, 'simple syrup');
INSERT INTO co.ingredients VALUES (22, 'aromatic bitters');
INSERT INTO co.ingredients VALUES (23, 'orange bitters');
INSERT INTO co.ingredients VALUES (24, 'raspberry syrup');
INSERT INTO co.ingredients VALUES (25, 'dry vermouth');
INSERT INTO co.ingredients VALUES (26, 'egg white');
INSERT INTO co.ingredients VALUES (27, 'lime juice');
INSERT INTO co.ingredients VALUES (28, 'whiskey');
INSERT INTO co.ingredients VALUES (29, 'sugar syrup');
INSERT INTO co.ingredients VALUES (30, 'carbonated water');
INSERT INTO co.ingredients VALUES (31, 'green chartreuse');
INSERT INTO co.ingredients VALUES (32, 'lime');
INSERT INTO co.ingredients VALUES (33, 'chartreuse');
INSERT INTO co.ingredients VALUES (34, 'maraschino liqueur');
INSERT INTO co.ingredients VALUES (35, 'rye whiskey');
INSERT INTO co.ingredients VALUES (36, 'angostura bitters');
INSERT INTO co.ingredients VALUES (37, 'grenadine');
INSERT INTO co.ingredients VALUES (38, 'orange juice');
INSERT INTO co.ingredients VALUES (39, 'absinthe');
INSERT INTO co.ingredients VALUES (40, 'dashes');
INSERT INTO co.ingredients VALUES (41, 'jamaican');
INSERT INTO co.ingredients VALUES (42, 'sugar cane');
INSERT INTO co.ingredients VALUES (43, 'port');
INSERT INTO co.ingredients VALUES (44, 'egg yolk');
INSERT INTO co.ingredients VALUES (45, 'scotch whisky');
INSERT INTO co.ingredients VALUES (46, 'drambuie');
INSERT INTO co.ingredients VALUES (47, 'sugar');
INSERT INTO co.ingredients VALUES (48, 'peychaud''s bitters');
INSERT INTO co.ingredients VALUES (49, 'crème de menthe');
INSERT INTO co.ingredients VALUES (50, 'bar spoon');
INSERT INTO co.ingredients VALUES (51, 'prosecco');
INSERT INTO co.ingredients VALUES (52, 'peach');
INSERT INTO co.ingredients VALUES (53, 'vodka');
INSERT INTO co.ingredients VALUES (54, 'coffee liqueur');
INSERT INTO co.ingredients VALUES (55, 'cl');
INSERT INTO co.ingredients VALUES (56, 'worcestershire sauce');
INSERT INTO co.ingredients VALUES (57, 'tabasco sauce');
INSERT INTO co.ingredients VALUES (58, 'celery salt');
INSERT INTO co.ingredients VALUES (59, 'black pepper');
INSERT INTO co.ingredients VALUES (60, 'cachaça');
INSERT INTO co.ingredients VALUES (61, 'champagne');
INSERT INTO co.ingredients VALUES (62, 'sugar cube');
INSERT INTO co.ingredients VALUES (63, 'apple brandy');
INSERT INTO co.ingredients VALUES (64, 'cointreau');
INSERT INTO co.ingredients VALUES (65, 'cranberry juice');
INSERT INTO co.ingredients VALUES (66, 'cola');
INSERT INTO co.ingredients VALUES (67, 'amaretto');
INSERT INTO co.ingredients VALUES (68, 'orange-flavored liqueur');
INSERT INTO co.ingredients VALUES (69, 'galliano');
INSERT INTO co.ingredients VALUES (70, 'grapefruit juice');
INSERT INTO co.ingredients VALUES (71, 'ginger ale');
INSERT INTO co.ingredients VALUES (72, 'angostura bitter');
INSERT INTO co.ingredients VALUES (73, 'irish whiskey');
INSERT INTO co.ingredients VALUES (74, 'coffee');
INSERT INTO co.ingredients VALUES (75, 'brown sugar');
INSERT INTO co.ingredients VALUES (76, 'wine');
INSERT INTO co.ingredients VALUES (77, 'white wine');
INSERT INTO co.ingredients VALUES (78, 'crème de cassis');
INSERT INTO co.ingredients VALUES (79, 'tequila');
INSERT INTO co.ingredients VALUES (80, 'amber jamaican rum');
INSERT INTO co.ingredients VALUES (81, 'martinique molasses rum');
INSERT INTO co.ingredients VALUES (82, 'orgeat syrup');
INSERT INTO co.ingredients VALUES (83, 'agave');
INSERT INTO co.ingredients VALUES (84, 'mint');
INSERT INTO co.ingredients VALUES (85, 'ginger beer');
INSERT INTO co.ingredients VALUES (86, 'pisco');
INSERT INTO co.ingredients VALUES (87, 'schnapps');
INSERT INTO co.ingredients VALUES (88, 'cherry brandy');
INSERT INTO co.ingredients VALUES (89, 'bénédictine');
INSERT INTO co.ingredients VALUES (90, 'pineapple juice');
INSERT INTO co.ingredients VALUES (91, 'grenadine syrup');
INSERT INTO co.ingredients VALUES (92, 'lillet');
INSERT INTO co.ingredients VALUES (93, 'falernum');
INSERT INTO co.ingredients VALUES (94, 'pernod');
INSERT INTO co.ingredients VALUES (95, 'honey');
INSERT INTO co.ingredients VALUES (96, 'goslings rum');
INSERT INTO co.ingredients VALUES (97, 'kahlúa');
INSERT INTO co.ingredients VALUES (98, 'espresso');
INSERT INTO co.ingredients VALUES (99, 'fernet-branca');
INSERT INTO co.ingredients VALUES (100, 'chambord raspberry liqueur');
INSERT INTO co.ingredients VALUES (101, 'mezcal');
INSERT INTO co.ingredients VALUES (102, 'yellow chartreuse');
INSERT INTO co.ingredients VALUES (103, 'aperol');
INSERT INTO co.ingredients VALUES (104, 'shiraz');
INSERT INTO co.ingredients VALUES (105, 'amaro');
INSERT INTO co.ingredients VALUES (106, 'whisky');
INSERT INTO co.ingredients VALUES (107, 'blended scotch whisky');
INSERT INTO co.ingredients VALUES (108, 'lagavulin 16y whisky');
INSERT INTO co.ingredients VALUES (109, 'select');
INSERT INTO co.ingredients VALUES (110, 'agave syrup');
INSERT INTO co.ingredients VALUES (111, 'grappa');

SELECT pg_catalog.setval('co.ingredients_ingredient_id_seq', 111, true);



--cocktailsxingredients:

INSERT INTO co.t_cocktails_x_ingredients VALUES (1, 1);
INSERT INTO co.t_cocktails_x_ingredients VALUES (1, 2);
INSERT INTO co.t_cocktails_x_ingredients VALUES (1, 3);
INSERT INTO co.t_cocktails_x_ingredients VALUES (2, 4);
INSERT INTO co.t_cocktails_x_ingredients VALUES (2, 5);
INSERT INTO co.t_cocktails_x_ingredients VALUES (2, 6);
INSERT INTO co.t_cocktails_x_ingredients VALUES (3, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (3, 8);
INSERT INTO co.t_cocktails_x_ingredients VALUES (3, 9);
INSERT INTO co.t_cocktails_x_ingredients VALUES (4, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (4, 10);
INSERT INTO co.t_cocktails_x_ingredients VALUES (4, 11);
INSERT INTO co.t_cocktails_x_ingredients VALUES (5, 1);
INSERT INTO co.t_cocktails_x_ingredients VALUES (5, 12);
INSERT INTO co.t_cocktails_x_ingredients VALUES (5, 13);
INSERT INTO co.t_cocktails_x_ingredients VALUES (5, 14);
INSERT INTO co.t_cocktails_x_ingredients VALUES (5, 15);
INSERT INTO co.t_cocktails_x_ingredients VALUES (6, 16);
INSERT INTO co.t_cocktails_x_ingredients VALUES (6, 17);
INSERT INTO co.t_cocktails_x_ingredients VALUES (6, 5);
INSERT INTO co.t_cocktails_x_ingredients VALUES (6, 4);
INSERT INTO co.t_cocktails_x_ingredients VALUES (7, 18);
INSERT INTO co.t_cocktails_x_ingredients VALUES (7, 19);
INSERT INTO co.t_cocktails_x_ingredients VALUES (7, 20);
INSERT INTO co.t_cocktails_x_ingredients VALUES (7, 15);
INSERT INTO co.t_cocktails_x_ingredients VALUES (7, 21);
INSERT INTO co.t_cocktails_x_ingredients VALUES (7, 22);
INSERT INTO co.t_cocktails_x_ingredients VALUES (8, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (8, 10);
INSERT INTO co.t_cocktails_x_ingredients VALUES (8, 23);
INSERT INTO co.t_cocktails_x_ingredients VALUES (9, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (9, 15);
INSERT INTO co.t_cocktails_x_ingredients VALUES (9, 24);
INSERT INTO co.t_cocktails_x_ingredients VALUES (9, 25);
INSERT INTO co.t_cocktails_x_ingredients VALUES (9, 26);
INSERT INTO co.t_cocktails_x_ingredients VALUES (10, 12);
INSERT INTO co.t_cocktails_x_ingredients VALUES (10, 14);
INSERT INTO co.t_cocktails_x_ingredients VALUES (10, 27);
INSERT INTO co.t_cocktails_x_ingredients VALUES (11, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (11, 4);
INSERT INTO co.t_cocktails_x_ingredients VALUES (12, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (12, 28);
INSERT INTO co.t_cocktails_x_ingredients VALUES (12, 12);
INSERT INTO co.t_cocktails_x_ingredients VALUES (13, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (13, 4);
INSERT INTO co.t_cocktails_x_ingredients VALUES (14, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (14, 15);
INSERT INTO co.t_cocktails_x_ingredients VALUES (14, 29);
INSERT INTO co.t_cocktails_x_ingredients VALUES (14, 30);
INSERT INTO co.t_cocktails_x_ingredients VALUES (15, 31);
INSERT INTO co.t_cocktails_x_ingredients VALUES (15, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (15, 32);
INSERT INTO co.t_cocktails_x_ingredients VALUES (15, 33);
INSERT INTO co.t_cocktails_x_ingredients VALUES (15, 34);
INSERT INTO co.t_cocktails_x_ingredients VALUES (16, 28);
INSERT INTO co.t_cocktails_x_ingredients VALUES (16, 35);
INSERT INTO co.t_cocktails_x_ingredients VALUES (16, 4);
INSERT INTO co.t_cocktails_x_ingredients VALUES (16, 36);
INSERT INTO co.t_cocktails_x_ingredients VALUES (17, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (18, 12);
INSERT INTO co.t_cocktails_x_ingredients VALUES (18, 37);
INSERT INTO co.t_cocktails_x_ingredients VALUES (18, 10);
INSERT INTO co.t_cocktails_x_ingredients VALUES (19, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (19, 38);
INSERT INTO co.t_cocktails_x_ingredients VALUES (19, 39);
INSERT INTO co.t_cocktails_x_ingredients VALUES (19, 37);
INSERT INTO co.t_cocktails_x_ingredients VALUES (20, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (20, 4);
INSERT INTO co.t_cocktails_x_ingredients VALUES (20, 5);
INSERT INTO co.t_cocktails_x_ingredients VALUES (21, 28);
INSERT INTO co.t_cocktails_x_ingredients VALUES (21, 17);
INSERT INTO co.t_cocktails_x_ingredients VALUES (21, 40);
INSERT INTO co.t_cocktails_x_ingredients VALUES (22, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (22, 18);
INSERT INTO co.t_cocktails_x_ingredients VALUES (22, 38);
INSERT INTO co.t_cocktails_x_ingredients VALUES (23, 12);
INSERT INTO co.t_cocktails_x_ingredients VALUES (23, 41);
INSERT INTO co.t_cocktails_x_ingredients VALUES (23, 32);
INSERT INTO co.t_cocktails_x_ingredients VALUES (23, 42);
INSERT INTO co.t_cocktails_x_ingredients VALUES (24, 43);
INSERT INTO co.t_cocktails_x_ingredients VALUES (24, 18);
INSERT INTO co.t_cocktails_x_ingredients VALUES (24, 44);
INSERT INTO co.t_cocktails_x_ingredients VALUES (25, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (25, 28);
INSERT INTO co.t_cocktails_x_ingredients VALUES (25, 12);
INSERT INTO co.t_cocktails_x_ingredients VALUES (26, 45);
INSERT INTO co.t_cocktails_x_ingredients VALUES (26, 46);
INSERT INTO co.t_cocktails_x_ingredients VALUES (27, 1);
INSERT INTO co.t_cocktails_x_ingredients VALUES (27, 39);
INSERT INTO co.t_cocktails_x_ingredients VALUES (27, 47);
INSERT INTO co.t_cocktails_x_ingredients VALUES (27, 48);
INSERT INTO co.t_cocktails_x_ingredients VALUES (28, 1);
INSERT INTO co.t_cocktails_x_ingredients VALUES (28, 13);
INSERT INTO co.t_cocktails_x_ingredients VALUES (28, 15);
INSERT INTO co.t_cocktails_x_ingredients VALUES (29, 1);
INSERT INTO co.t_cocktails_x_ingredients VALUES (29, 49);
INSERT INTO co.t_cocktails_x_ingredients VALUES (30, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (30, 4);
INSERT INTO co.t_cocktails_x_ingredients VALUES (30, 10);
INSERT INTO co.t_cocktails_x_ingredients VALUES (30, 39);
INSERT INTO co.t_cocktails_x_ingredients VALUES (30, 23);
INSERT INTO co.t_cocktails_x_ingredients VALUES (31, 35);
INSERT INTO co.t_cocktails_x_ingredients VALUES (31, 1);
INSERT INTO co.t_cocktails_x_ingredients VALUES (31, 4);
INSERT INTO co.t_cocktails_x_ingredients VALUES (31, 50);
INSERT INTO co.t_cocktails_x_ingredients VALUES (31, 40);
INSERT INTO co.t_cocktails_x_ingredients VALUES (32, 28);
INSERT INTO co.t_cocktails_x_ingredients VALUES (32, 16);
INSERT INTO co.t_cocktails_x_ingredients VALUES (32, 15);
INSERT INTO co.t_cocktails_x_ingredients VALUES (32, 21);
INSERT INTO co.t_cocktails_x_ingredients VALUES (33, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (33, 13);
INSERT INTO co.t_cocktails_x_ingredients VALUES (34, 51);
INSERT INTO co.t_cocktails_x_ingredients VALUES (34, 52);
INSERT INTO co.t_cocktails_x_ingredients VALUES (35, 53);
INSERT INTO co.t_cocktails_x_ingredients VALUES (35, 54);
INSERT INTO co.t_cocktails_x_ingredients VALUES (36, 53);
INSERT INTO co.t_cocktails_x_ingredients VALUES (36, 55);
INSERT INTO co.t_cocktails_x_ingredients VALUES (36, 15);
INSERT INTO co.t_cocktails_x_ingredients VALUES (36, 56);
INSERT INTO co.t_cocktails_x_ingredients VALUES (36, 57);
INSERT INTO co.t_cocktails_x_ingredients VALUES (36, 58);
INSERT INTO co.t_cocktails_x_ingredients VALUES (36, 59);
INSERT INTO co.t_cocktails_x_ingredients VALUES (37, 60);
INSERT INTO co.t_cocktails_x_ingredients VALUES (37, 32);
INSERT INTO co.t_cocktails_x_ingredients VALUES (37, 47);
INSERT INTO co.t_cocktails_x_ingredients VALUES (38, 61);
INSERT INTO co.t_cocktails_x_ingredients VALUES (38, 1);
INSERT INTO co.t_cocktails_x_ingredients VALUES (38, 36);
INSERT INTO co.t_cocktails_x_ingredients VALUES (38, 62);
INSERT INTO co.t_cocktails_x_ingredients VALUES (39, 1);
INSERT INTO co.t_cocktails_x_ingredients VALUES (39, 63);
INSERT INTO co.t_cocktails_x_ingredients VALUES (39, 4);
INSERT INTO co.t_cocktails_x_ingredients VALUES (40, 53);
INSERT INTO co.t_cocktails_x_ingredients VALUES (40, 64);
INSERT INTO co.t_cocktails_x_ingredients VALUES (40, 27);
INSERT INTO co.t_cocktails_x_ingredients VALUES (40, 65);
INSERT INTO co.t_cocktails_x_ingredients VALUES (41, 12);
INSERT INTO co.t_cocktails_x_ingredients VALUES (41, 66);
INSERT INTO co.t_cocktails_x_ingredients VALUES (41, 14);
INSERT INTO co.t_cocktails_x_ingredients VALUES (42, 61);
INSERT INTO co.t_cocktails_x_ingredients VALUES (42, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (42, 21);
INSERT INTO co.t_cocktails_x_ingredients VALUES (42, 15);
INSERT INTO co.t_cocktails_x_ingredients VALUES (43, 1);
INSERT INTO co.t_cocktails_x_ingredients VALUES (43, 67);
INSERT INTO co.t_cocktails_x_ingredients VALUES (44, 68);
INSERT INTO co.t_cocktails_x_ingredients VALUES (44, 69);
INSERT INTO co.t_cocktails_x_ingredients VALUES (44, 13);
INSERT INTO co.t_cocktails_x_ingredients VALUES (44, 38);
INSERT INTO co.t_cocktails_x_ingredients VALUES (44, 3);
INSERT INTO co.t_cocktails_x_ingredients VALUES (45, 2);
INSERT INTO co.t_cocktails_x_ingredients VALUES (45, 49);
INSERT INTO co.t_cocktails_x_ingredients VALUES (45, 3);
INSERT INTO co.t_cocktails_x_ingredients VALUES (46, 12);
INSERT INTO co.t_cocktails_x_ingredients VALUES (46, 70);
INSERT INTO co.t_cocktails_x_ingredients VALUES (46, 10);
INSERT INTO co.t_cocktails_x_ingredients VALUES (46, 27);
INSERT INTO co.t_cocktails_x_ingredients VALUES (47, 18);
INSERT INTO co.t_cocktails_x_ingredients VALUES (47, 71);
INSERT INTO co.t_cocktails_x_ingredients VALUES (47, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (48, 73);
INSERT INTO co.t_cocktails_x_ingredients VALUES (48, 74);
INSERT INTO co.t_cocktails_x_ingredients VALUES (48, 3);
INSERT INTO co.t_cocktails_x_ingredients VALUES (48, 75);
INSERT INTO co.t_cocktails_x_ingredients VALUES (49, 76);
INSERT INTO co.t_cocktails_x_ingredients VALUES (49, 77);
INSERT INTO co.t_cocktails_x_ingredients VALUES (49, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (50, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (50, 79);
INSERT INTO co.t_cocktails_x_ingredients VALUES (50, 53);
INSERT INTO co.t_cocktails_x_ingredients VALUES (50, 12);
INSERT INTO co.t_cocktails_x_ingredients VALUES (50, 13);
INSERT INTO co.t_cocktails_x_ingredients VALUES (50, 14);
INSERT INTO co.t_cocktails_x_ingredients VALUES (50, 64);
INSERT INTO co.t_cocktails_x_ingredients VALUES (50, 15);
INSERT INTO co.t_cocktails_x_ingredients VALUES (50, 21);
INSERT INTO co.t_cocktails_x_ingredients VALUES (50, 66);
INSERT INTO co.t_cocktails_x_ingredients VALUES (51, 12);
INSERT INTO co.t_cocktails_x_ingredients VALUES (51, 80);
INSERT INTO co.t_cocktails_x_ingredients VALUES (51, 81);
INSERT INTO co.t_cocktails_x_ingredients VALUES (51, 20);
INSERT INTO co.t_cocktails_x_ingredients VALUES (51, 82);
INSERT INTO co.t_cocktails_x_ingredients VALUES (51, 27);
INSERT INTO co.t_cocktails_x_ingredients VALUES (51, 21);
INSERT INTO co.t_cocktails_x_ingredients VALUES (52, 79);
INSERT INTO co.t_cocktails_x_ingredients VALUES (52, 83);
INSERT INTO co.t_cocktails_x_ingredients VALUES (52, 13);
INSERT INTO co.t_cocktails_x_ingredients VALUES (52, 32);
INSERT INTO co.t_cocktails_x_ingredients VALUES (53, 61);
INSERT INTO co.t_cocktails_x_ingredients VALUES (53, 38);
INSERT INTO co.t_cocktails_x_ingredients VALUES (54, 16);
INSERT INTO co.t_cocktails_x_ingredients VALUES (54, 84);
INSERT INTO co.t_cocktails_x_ingredients VALUES (55, 12);
INSERT INTO co.t_cocktails_x_ingredients VALUES (55, 14);
INSERT INTO co.t_cocktails_x_ingredients VALUES (55, 27);
INSERT INTO co.t_cocktails_x_ingredients VALUES (55, 84);
INSERT INTO co.t_cocktails_x_ingredients VALUES (55, 47);
INSERT INTO co.t_cocktails_x_ingredients VALUES (56, 53);
INSERT INTO co.t_cocktails_x_ingredients VALUES (56, 32);
INSERT INTO co.t_cocktails_x_ingredients VALUES (56, 85);
INSERT INTO co.t_cocktails_x_ingredients VALUES (57, 12);
INSERT INTO co.t_cocktails_x_ingredients VALUES (58, 86);
INSERT INTO co.t_cocktails_x_ingredients VALUES (58, 21);
INSERT INTO co.t_cocktails_x_ingredients VALUES (58, 26);
INSERT INTO co.t_cocktails_x_ingredients VALUES (59, 53);
INSERT INTO co.t_cocktails_x_ingredients VALUES (59, 65);
INSERT INTO co.t_cocktails_x_ingredients VALUES (59, 70);
INSERT INTO co.t_cocktails_x_ingredients VALUES (60, 53);
INSERT INTO co.t_cocktails_x_ingredients VALUES (60, 87);
INSERT INTO co.t_cocktails_x_ingredients VALUES (60, 38);
INSERT INTO co.t_cocktails_x_ingredients VALUES (60, 65);
INSERT INTO co.t_cocktails_x_ingredients VALUES (61, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (61, 88);
INSERT INTO co.t_cocktails_x_ingredients VALUES (61, 64);
INSERT INTO co.t_cocktails_x_ingredients VALUES (61, 89);
INSERT INTO co.t_cocktails_x_ingredients VALUES (61, 37);
INSERT INTO co.t_cocktails_x_ingredients VALUES (61, 90);
INSERT INTO co.t_cocktails_x_ingredients VALUES (61, 27);
INSERT INTO co.t_cocktails_x_ingredients VALUES (61, 36);
INSERT INTO co.t_cocktails_x_ingredients VALUES (62, 79);
INSERT INTO co.t_cocktails_x_ingredients VALUES (62, 38);
INSERT INTO co.t_cocktails_x_ingredients VALUES (62, 91);
INSERT INTO co.t_cocktails_x_ingredients VALUES (63, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (63, 53);
INSERT INTO co.t_cocktails_x_ingredients VALUES (63, 92);
INSERT INTO co.t_cocktails_x_ingredients VALUES (64, 12);
INSERT INTO co.t_cocktails_x_ingredients VALUES (64, 32);
INSERT INTO co.t_cocktails_x_ingredients VALUES (64, 93);
INSERT INTO co.t_cocktails_x_ingredients VALUES (64, 37);
INSERT INTO co.t_cocktails_x_ingredients VALUES (64, 36);
INSERT INTO co.t_cocktails_x_ingredients VALUES (64, 94);
INSERT INTO co.t_cocktails_x_ingredients VALUES (65, 12);
INSERT INTO co.t_cocktails_x_ingredients VALUES (65, 69);
INSERT INTO co.t_cocktails_x_ingredients VALUES (65, 90);
INSERT INTO co.t_cocktails_x_ingredients VALUES (65, 27);
INSERT INTO co.t_cocktails_x_ingredients VALUES (65, 51);
INSERT INTO co.t_cocktails_x_ingredients VALUES (66, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (67, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (68, 12);
INSERT INTO co.t_cocktails_x_ingredients VALUES (68, 32);
INSERT INTO co.t_cocktails_x_ingredients VALUES (68, 95);
INSERT INTO co.t_cocktails_x_ingredients VALUES (69, 12);
INSERT INTO co.t_cocktails_x_ingredients VALUES (69, 96);
INSERT INTO co.t_cocktails_x_ingredients VALUES (69, 85);
INSERT INTO co.t_cocktails_x_ingredients VALUES (70, 53);
INSERT INTO co.t_cocktails_x_ingredients VALUES (70, 97);
INSERT INTO co.t_cocktails_x_ingredients VALUES (70, 29);
INSERT INTO co.t_cocktails_x_ingredients VALUES (70, 98);
INSERT INTO co.t_cocktails_x_ingredients VALUES (71, 99);
INSERT INTO co.t_cocktails_x_ingredients VALUES (71, 66);
INSERT INTO co.t_cocktails_x_ingredients VALUES (72, 53);
INSERT INTO co.t_cocktails_x_ingredients VALUES (72, 100);
INSERT INTO co.t_cocktails_x_ingredients VALUES (72, 90);
INSERT INTO co.t_cocktails_x_ingredients VALUES (73, 101);
INSERT INTO co.t_cocktails_x_ingredients VALUES (73, 12);
INSERT INTO co.t_cocktails_x_ingredients VALUES (73, 93);
INSERT INTO co.t_cocktails_x_ingredients VALUES (73, 10);
INSERT INTO co.t_cocktails_x_ingredients VALUES (73, 32);
INSERT INTO co.t_cocktails_x_ingredients VALUES (73, 21);
INSERT INTO co.t_cocktails_x_ingredients VALUES (74, 53);
INSERT INTO co.t_cocktails_x_ingredients VALUES (75, 101);
INSERT INTO co.t_cocktails_x_ingredients VALUES (75, 102);
INSERT INTO co.t_cocktails_x_ingredients VALUES (75, 103);
INSERT INTO co.t_cocktails_x_ingredients VALUES (75, 32);
INSERT INTO co.t_cocktails_x_ingredients VALUES (76, 28);
INSERT INTO co.t_cocktails_x_ingredients VALUES (76, 21);
INSERT INTO co.t_cocktails_x_ingredients VALUES (76, 104);
INSERT INTO co.t_cocktails_x_ingredients VALUES (77, 12);
INSERT INTO co.t_cocktails_x_ingredients VALUES (77, 21);
INSERT INTO co.t_cocktails_x_ingredients VALUES (77, 36);
INSERT INTO co.t_cocktails_x_ingredients VALUES (77, 61);
INSERT INTO co.t_cocktails_x_ingredients VALUES (78, 79);
INSERT INTO co.t_cocktails_x_ingredients VALUES (79, 16);
INSERT INTO co.t_cocktails_x_ingredients VALUES (79, 105);
INSERT INTO co.t_cocktails_x_ingredients VALUES (79, 103);
INSERT INTO co.t_cocktails_x_ingredients VALUES (80, 106);
INSERT INTO co.t_cocktails_x_ingredients VALUES (80, 107);
INSERT INTO co.t_cocktails_x_ingredients VALUES (80, 108);
INSERT INTO co.t_cocktails_x_ingredients VALUES (81, 53);
INSERT INTO co.t_cocktails_x_ingredients VALUES (81, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (81, 15);
INSERT INTO co.t_cocktails_x_ingredients VALUES (82, 7);
INSERT INTO co.t_cocktails_x_ingredients VALUES (83, 51);
INSERT INTO co.t_cocktails_x_ingredients VALUES (83, 109);
INSERT INTO co.t_cocktails_x_ingredients VALUES (83, 6);
INSERT INTO co.t_cocktails_x_ingredients VALUES (85, 73);
INSERT INTO co.t_cocktails_x_ingredients VALUES (85, 4);
INSERT INTO co.t_cocktails_x_ingredients VALUES (85, 33);
INSERT INTO co.t_cocktails_x_ingredients VALUES (85, 36);
INSERT INTO co.t_cocktails_x_ingredients VALUES (86, 79);
INSERT INTO co.t_cocktails_x_ingredients VALUES (86, 27);
INSERT INTO co.t_cocktails_x_ingredients VALUES (86, 110);
INSERT INTO co.t_cocktails_x_ingredients VALUES (87, 36);
INSERT INTO co.t_cocktails_x_ingredients VALUES (87, 82);
INSERT INTO co.t_cocktails_x_ingredients VALUES (87, 35);
INSERT INTO co.t_cocktails_x_ingredients VALUES (88, 111);
INSERT INTO co.t_cocktails_x_ingredients VALUES (89, 12);
INSERT INTO co.t_cocktails_x_ingredients VALUES (89, 14);
INSERT INTO co.t_cocktails_x_ingredients VALUES (89, 69);
INSERT INTO co.t_cocktails_x_ingredients VALUES (89, 13);
INSERT INTO co.t_cocktails_x_ingredients VALUES (89, 27);

SELECT pg_catalog.setval('co.t_cocktails_x_ingredients_cocktail_id_seq', 1, false);

